# Generated by Django 3.1.14 on 2022-08-09 07:01

from django.db import migrations, models
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ('edc_senaite_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senaiteuser',
            name='related_username',
            field=models.CharField(max_length=200, null=True, verbose_name='EDC related username'),
        ),
        migrations.AlterField(
            model_name='senaiteuser',
            name='password',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text='Senaite LIMS password (Encryption: RSA local)', max_length=71, null=True, verbose_name='Senaite LIMS password'),
        ),
        migrations.AlterField(
            model_name='senaiteuser',
            name='username',
            field=models.CharField(max_length=200, null=True, verbose_name='Senaite username'),
        ),
    ]
