# Generated by Django 3.1.14 on 2023-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_senaite_interface', '0003_historicalsenaiteresult_historicalsenaiteresultvalue_senaiteresult_senaiteresultvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsenaiteresult',
            name='parent_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Primary sample ID, if partition'),
        ),
        migrations.AlterField(
            model_name='senaiteresult',
            name='parent_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Primary sample ID, if partition'),
        ),
    ]
