# Generated by Django 3.1.14 on 2023-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_senaite_interface', '0004_auto_20230404_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsenaiteresultvalue',
            name='analysis_keyword',
            field=models.CharField(max_length=50, verbose_name='Unique keyword used to identify the analysis'),
        ),
        migrations.AlterField(
            model_name='senaiteresultvalue',
            name='analysis_keyword',
            field=models.CharField(max_length=50, verbose_name='Unique keyword used to identify the analysis'),
        ),
        migrations.AlterUniqueTogether(
            name='senaiteresultvalue',
            unique_together={('result', 'analysis_keyword')},
        ),
    ]
